$axure.loadCurrentPage({
  "url":"home.html",
  "generationDate":new Date(1565724985274.62),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"Usuario"],
  "page":{
    "packageId":"6e2b430f1a6f43b593ef9ab7686bb332",
    "type":"Axure:Page",
    "name":"Home",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e2394d20e8b44a8c9f33eb807118f723",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF9933},
            "location":{
              "x":230,
              "y":40},
            "size":{
              "width":580,
              "height":390},
            "cornerRadiusTopLeft":"5",
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b613a5e28af64518b030e63febe5590e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF9933},
                "location":{
                  "x":230,
                  "y":40},
                "size":{
                  "width":580,
                  "height":390},
                "cornerRadiusTopLeft":"5",
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"93de5dd524504a5884b7238f8e0dcdaa",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "location":{
              "x":380,
              "y":215},
            "size":{
              "width":280,
              "height":45}},
          "adaptiveStyles":{
},
          "placeholderText":"Usuario"},
{
          "id":"c8f0ee53014d4b6e8696110ef8683128",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "location":{
              "x":380,
              "y":265},
            "size":{
              "width":280,
              "height":45}},
          "adaptiveStyles":{
},
          "placeholderText":"Clave"},
{
          "id":"d4fece38f24242b1be017d8f1c58740b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":455,
              "y":80},
            "size":{
              "width":120,
              "height":84}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6672faa0e36c469ca4ae954cf3bd62e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":455,
                  "y":80},
                "size":{
                  "width":120,
                  "height":84}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"d5403b5e3a17405ba34d87f887c29491",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000CC,
              "opacity":1},
            "location":{
              "x":380,
              "y":350},
            "size":{
              "width":280,
              "height":40}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open MainMenu in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"mainmenu.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"59365d1fb2e248c0a02014593728dd5d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"right",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":370,
              "y":180},
            "size":{
              "width":280,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff0c3679b21b44bfb74e27caf61c61cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":370,
                  "y":180},
                "size":{
                  "width":280,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "e2394d20e8b44a8c9f33eb807118f723":{
      "scriptId":"u0"},
    "b613a5e28af64518b030e63febe5590e":{
      "scriptId":"u1"},
    "93de5dd524504a5884b7238f8e0dcdaa":{
      "scriptId":"u2"},
    "c8f0ee53014d4b6e8696110ef8683128":{
      "scriptId":"u3"},
    "d4fece38f24242b1be017d8f1c58740b":{
      "scriptId":"u4"},
    "6672faa0e36c469ca4ae954cf3bd62e6":{
      "scriptId":"u5"},
    "d5403b5e3a17405ba34d87f887c29491":{
      "scriptId":"u6"},
    "59365d1fb2e248c0a02014593728dd5d":{
      "scriptId":"u7"},
    "ff0c3679b21b44bfb74e27caf61c61cd":{
      "scriptId":"u8"}}});