$axure.loadCurrentPage({
  "url":"agentes.html",
  "generationDate":new Date(1565724986393.39),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"Usuario"],
  "page":{
    "packageId":"13fb5fe2df164e83b05a147e3f3b6315",
    "type":"Axure:Page",
    "name":"Agentes",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"dd3f55c4456e46c2ae68286d08dd4748",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":9,
              "y":0},
            "size":{
              "width":81,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"927065d81117407e8563288417391e40",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":9,
                  "y":0},
                "size":{
                  "width":81,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"e2a9b85c600b4e8bbc8d6a847ff784f4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":50},
            "size":{
              "width":90,
              "height":20},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad7162356ea941c8886b7ae90f10e39f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":50},
                "size":{
                  "width":90,
                  "height":20},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/prospectos/u2.png"}},
{
          "id":"389dd7e1482f44dfb0676476ebde0375",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":910,
              "y":10},
            "size":{
              "width":30,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"538e00535e5e47269c9bdaf7e05a0035",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":910,
                  "y":10},
                "size":{
                  "width":30,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open MainMenu in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"mainmenu.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/prospectos/u6.png"}},
{
          "id":"299dfc56e38049c1854e4629eede391f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":-3},
            "size":{
              "width":230,
              "height":63}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c6912cc59fd4e568607bdb86c790ced",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":-3},
                "size":{
                  "width":230,
                  "height":63}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/agentes/u6.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "dd3f55c4456e46c2ae68286d08dd4748":{
      "scriptId":"u0"},
    "927065d81117407e8563288417391e40":{
      "scriptId":"u1"},
    "e2a9b85c600b4e8bbc8d6a847ff784f4":{
      "scriptId":"u2"},
    "ad7162356ea941c8886b7ae90f10e39f":{
      "scriptId":"u3"},
    "389dd7e1482f44dfb0676476ebde0375":{
      "scriptId":"u4"},
    "538e00535e5e47269c9bdaf7e05a0035":{
      "scriptId":"u5"},
    "299dfc56e38049c1854e4629eede391f":{
      "scriptId":"u6"},
    "0c6912cc59fd4e568607bdb86c790ced":{
      "scriptId":"u7"}}});