$axure.loadCurrentPage({
  "url":"mainmenu.html",
  "generationDate":new Date(1565724985617.77),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"Usuario"],
  "page":{
    "packageId":"2c9e795252904ce6a391dd7b98766863",
    "type":"Axure:Page",
    "name":"MainMenu",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"12f17f209c024b178543b7a66fdf0276",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-154,
              "y":-310.000030517578},
            "size":{
              "width":1358,
              "height":1080}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df49ed9ff3554dc1abfc40367a26aa39",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-154,
                  "y":-310.000030517578},
                "size":{
                  "width":1358,
                  "height":1080}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/mainmenu/u0.png"}},
{
          "id":"e6985344fc9749dd90990baaf046e5da",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":9,
              "y":0},
            "size":{
              "width":261,
              "height":160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f11e4cf34725438b9c8ebe2a6c2a2ea4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":9,
                  "y":0},
                "size":{
                  "width":261,
                  "height":160}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"e690649deb774f4ea9146fcb9294a728",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":327.5,
              "y":0},
            "size":{
              "width":876,
              "height":161},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4fd01a6feb5741b5b4ca83f230a7913c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":327.5,
                  "y":0},
                "size":{
                  "width":876,
                  "height":161},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/mainmenu/u4.png"}},
{
          "id":"8fac96f362ba45b5a54420de0b401ef5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":180},
            "size":{
              "width":290,
              "height":200}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"979c38033a8a4996a8abef6adbdb5c44",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":180},
                "size":{
                  "width":290,
                  "height":200}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Prospectos in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"prospectos.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/mainmenu/u6.png"}},
{
          "id":"973d980253394093922ad0b84070bf7b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":180},
            "size":{
              "width":290,
              "height":200}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ede64bf9d7c4d97969e32a3be95b241",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":180},
                "size":{
                  "width":290,
                  "height":200}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Clientes in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"clientes.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/mainmenu/u8.png"}},
{
          "id":"d7a2f71abe314de69098bc2a40b2c108",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":420},
            "size":{
              "width":300,
              "height":200}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2a851db1c334f0ea810850b18ba9919",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":420},
                "size":{
                  "width":300,
                  "height":200}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Agentes in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"agentes.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/mainmenu/u10.png"}},
{
          "id":"6ca1970017954bc7a3f8458de2f5ddcf",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":650,
              "y":420},
            "size":{
              "width":300,
              "height":200}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef7af8717efe4d6e953217301e8c8bf1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":650,
                  "y":420},
                "size":{
                  "width":300,
                  "height":200}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Aseguradora in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"aseguradora.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/mainmenu/u12.png"}},
{
          "id":"ef6c0b53b5ab49d689dd7a240c54305d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":810,
              "y":180},
            "size":{
              "width":290,
              "height":200}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ccba9221edf34ef9acdeef1e6190536b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":810,
                  "y":180},
                "size":{
                  "width":290,
                  "height":200}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Productos in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"productos.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/mainmenu/u14.png"}},
{
          "id":"1b092b6228ae452c80bb76fa4912a6d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000CC,
              "opacity":1},
            "location":{
              "x":178,
              "y":380},
            "size":{
              "width":132,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2dc976f093e445829739df2ea7b5cc68",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000CC,
                  "opacity":1},
                "location":{
                  "x":178,
                  "y":380},
                "size":{
                  "width":132,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8b8d1907a2d341fd8246abe5c897b59c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000CC,
              "opacity":1},
            "location":{
              "x":605,
              "y":380},
            "size":{
              "width":95,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fdb7dbb4054f475badc534b06d739b3f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000CC,
                  "opacity":1},
                "location":{
                  "x":605,
                  "y":380},
                "size":{
                  "width":95,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"161e2c44362d4ddbb738b6ed3d414817",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000CC,
              "opacity":1},
            "location":{
              "x":981,
              "y":380},
            "size":{
              "width":119,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b13e4a39ee140088d0fd9a44b8710c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000CC,
                  "opacity":1},
                "location":{
                  "x":981,
                  "y":380},
                "size":{
                  "width":119,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"832dee489124415bb381339e24a6a81d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000CC,
              "opacity":1},
            "location":{
              "x":435,
              "y":620},
            "size":{
              "width":95,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f629b946fcf042d298e53ec35a63a915",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000CC,
                  "opacity":1},
                "location":{
                  "x":435,
                  "y":620},
                "size":{
                  "width":95,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3387325d3e464f3383f80fa55641127a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000CC,
              "opacity":1},
            "location":{
              "x":801,
              "y":620},
            "size":{
              "width":149,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76a359a48b9f47c0bf93b6dc7ea5b623",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000CC,
                  "opacity":1},
                "location":{
                  "x":801,
                  "y":620},
                "size":{
                  "width":149,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "12f17f209c024b178543b7a66fdf0276":{
      "scriptId":"u0"},
    "df49ed9ff3554dc1abfc40367a26aa39":{
      "scriptId":"u1"},
    "e6985344fc9749dd90990baaf046e5da":{
      "scriptId":"u2"},
    "f11e4cf34725438b9c8ebe2a6c2a2ea4":{
      "scriptId":"u3"},
    "e690649deb774f4ea9146fcb9294a728":{
      "scriptId":"u4"},
    "4fd01a6feb5741b5b4ca83f230a7913c":{
      "scriptId":"u5"},
    "8fac96f362ba45b5a54420de0b401ef5":{
      "scriptId":"u6"},
    "979c38033a8a4996a8abef6adbdb5c44":{
      "scriptId":"u7"},
    "973d980253394093922ad0b84070bf7b":{
      "scriptId":"u8"},
    "4ede64bf9d7c4d97969e32a3be95b241":{
      "scriptId":"u9"},
    "d7a2f71abe314de69098bc2a40b2c108":{
      "scriptId":"u10"},
    "c2a851db1c334f0ea810850b18ba9919":{
      "scriptId":"u11"},
    "6ca1970017954bc7a3f8458de2f5ddcf":{
      "scriptId":"u12"},
    "ef7af8717efe4d6e953217301e8c8bf1":{
      "scriptId":"u13"},
    "ef6c0b53b5ab49d689dd7a240c54305d":{
      "scriptId":"u14"},
    "ccba9221edf34ef9acdeef1e6190536b":{
      "scriptId":"u15"},
    "1b092b6228ae452c80bb76fa4912a6d4":{
      "scriptId":"u16"},
    "2dc976f093e445829739df2ea7b5cc68":{
      "scriptId":"u17"},
    "8b8d1907a2d341fd8246abe5c897b59c":{
      "scriptId":"u18"},
    "fdb7dbb4054f475badc534b06d739b3f":{
      "scriptId":"u19"},
    "161e2c44362d4ddbb738b6ed3d414817":{
      "scriptId":"u20"},
    "8b13e4a39ee140088d0fd9a44b8710c4":{
      "scriptId":"u21"},
    "832dee489124415bb381339e24a6a81d":{
      "scriptId":"u22"},
    "f629b946fcf042d298e53ec35a63a915":{
      "scriptId":"u23"},
    "3387325d3e464f3383f80fa55641127a":{
      "scriptId":"u24"},
    "76a359a48b9f47c0bf93b6dc7ea5b623":{
      "scriptId":"u25"}}});